### PR TITLE
Revamp UI/UX with structural refactoring

### PR DESCRIPTION
**Pull request by RajatRajdeep**
Preview: https://deploy-preview-56--musing-joliot-927680.netlify.app

**Major Changes:**
- Redesign the homepage UI
- Upgrade font awesome to v6.5.2
- Upgrade bootstrap to v5.1.3
- Refactored CSS styles into SCSS for better maintainability and scalability
- Remove Give A Talk and Request A Talk nav items and added it in Hero Banner
- Removed the [events](https://www.hydpy.org/events/), [category](https://www.hydpy.org/category/), [pyexpresshyd](https://www.hydpy.org/pyexpresshyd/) pages since there are no redirects leading to them on the website. These pages can be reconsidered and reinstated if necessary. @bhansa, @inovizz please confirm.
- Delete testimonial section from Home Page due to lack of added value
- Remove faq page and included all faqs in Home page
- Reorganise repository file structure for better maintainability
- Delete unused assets
- Delete unused html files

**Minor Changes:**
- Fix favicon not visible issue
- Accessibility fixes
- Reduce image sizes to reduce the latency
- Fix console errors
- Center align About and COC pages heading
- Add pydelhi logo
- Add X logo in social links

**TO DO:**
- [x] Update google analytics code

Thanks to @karunasolanki for the insightful review and valuable suggestions on UI/UX improvements.

### CODE REVIEW

**Comment by bhansa** [comment]
Hi @RajatRajdeep, thanks for taking up time to create this Pull request,  the changes looks good to me except few suggestions. 
Couple of suggestions and todo's:
 - I am not sure if we need to have pyexpress on the website, I believe there is a separate website for python express where we run these events. _Please confirm with the team internally_
 - In terms of removing events from page I would suggest to have them for SEO purposes, if possible to fetch the data from meetup lets do that. 
 _This is good to have, if it requires too much work we can skip._
 - I think we can use different design for hero banner as the current one is not able to highlight the Title and CTA's on the website. [Here](https://www.justinmind.com/blog/inspiring-hero-image-websites/) is a blog which I found about hero designs.
   I can see some contrast issues due to this on the page [1].
 - Increase contrast for header navigation links. Make them bold or use _font weight_ as 600
 - FAQ list is not accessible, when tabbed the the element does not react to focus state. Use _:focus_ state styles to apply border when focused.


I am creating separate issues for enhancement request.



[1]
image

**Comment by rootvertex** [comment]
Thanks for the PR, @RajatRajdeep!

Please consider the below feedback.

1. I think the text "Community driven group for promoting python in Hyderabad." can be in a different style (less highlighted) than the landing text, "Hyderabad Python User group".
2. on [About page](https://deploy-preview-56--musing-joliot-927680.netlify.app/about/)
    a. Need to update the Telegram link to `t.me/HydPy` instead of `t.me/JoinHydPy` in "Please join our..." sentence.
    b. "Come for the Language, Stay for the Community !" => "Come for the Language, Stay for the Community!" (no whitespace before exclamation mark)
3. We should update the names in CoC contact information [page](https://deploy-preview-56--musing-joliot-927680.netlify.app/coc/).
4. Update Telegram link in the `[Telegram Group Invitation](https://bit.ly/joinhydpy)` part on Home page in FAQs section (3rd question).

**Comment by bkamapantula** [comment]
Thanks for the PR, @RajatRajdeep!

Please consider the below feedback.

1.  I think the text "Community driven group for promoting python in Hyderabad." can be in a different style (less highlighted) than the landing text, "Hyderabad Python User group".
2. on [About page](https://deploy-preview-56--musing-joliot-927680.netlify.app/about/)
    a. Need to update the Telegram link to t.me/HydPy instead of t.me/JoinHydPy in "Please join our..." sentence.
    b. "Come for the Language, Stay for the Community !" => "Come for the Language, Stay for the Community!" (no whitespace before exclamation mark)
3. We should update the names in CoC contact information [page](https://deploy-preview-56--musing-joliot-927680.netlify.app/coc/).
4. Update Telegram link in the [Telegram Group Invitation](https://bit.ly/joinhydpy) part on Home page in FAQs section (3rd question).

**Comment by RajatRajdeep** [comment]
Thanks @bhansa and @bkamapantula for reviewing the changes and feedbacks!

Response to https://github.com/HydPy/HydPy/pull/56#issuecomment-2260539889
1. Python express: The website built last year is not up. It can be added later once it's hosted by someone.
2. Events page: I’ll work on fetching the events from meet-up page and will be raising a subsequent CL. The following issue is already created for that: https://github.com/HydPy/HydPy/issues/54
3. Hero Banner: Due to wave tool limitation the background image is not considered as background in checking contrast that’s why it’s highlighting an error.
5. Increase contrast for header navigation links by increasing font-size and changing the color from grey to black.
6. FAQ list is now accessible.

Response to https://github.com/HydPy/HydPy/pull/56#issuecomment-2308022837
Made all the changes expect addition of COC Point of contacts, will do that after confirmation in subsequent PR

**Review by bhansa — APPROVED** [review]

**Pull request merged**
