### PR TITLE
added pyconf promo

### PR DESCRIPTION
**Pull request by bhansa**
image

Feel free to suggest any changes. #10

### CODE REVIEW

**Comment by manitha** [comment]
Promo is added as part of Hero/banner page - either as background or slide show. Current one is needs changes.

**Comment by bhansa** [comment]
I just put it into the top so attracts more attention when user lands on the page.

**Comment by ananyo2012** [comment]
@bhansa Can we try this with a bootstrap alert box ? They look pretty cool.

**Comment by bhansa** [comment]
Sure, @ananyo2012

**Comment by ananyo2012** [comment]
@bhansa Can you make the changes as I said so we can have a look.

**Comment by bhansa** [comment]
Preview URL : [Preview](https://bhansa.github.io/HydPy/)

**Comment by ananyo2012** [comment]
Looks good. But we can improve it a bit more.
- Use PyConf Hyderabad instead of Python Conference Hyderabad everywhere.
- The [previous banner content](https://github.com/HydPy/HydPy/pull/11#issue-251722859) looks much better. We should use the exact content from that. Even for the button texts as well.
- Instead of putting the heading in white space we should have it just over the image. The whitespace doesn't look good as of now.

**Comment by bhansa** [comment]
@ananyo2012 can you take a pull and customize it, see if you can get a banner with the heading too so we don't have to put it explicitly and just replace this one.

**Comment by manitha** [comment]
pyconf is complete. Will close this PR

**Pull request closed without merging**
